import React from 'react';
import { HelpCircle, Info, Sparkles } from 'lucide-react';
import { ReasoningStep } from '../types/factCheck';

interface ReasoningSectionProps {
  reasoning?: ReasoningStep[];
  verdict: string;
}

export const ReasoningSection: React.FC<ReasoningSectionProps> = ({ reasoning, verdict }) => {
  if (!reasoning || reasoning.length === 0) return null;

  return (
    <div className="bg-white rounded-xl border border-stone-200/90 p-6 sm:p-7 mb-7">
      <div className="flex items-center gap-2 mb-2 pb-3 border-b border-stone-100">
        <HelpCircle className="w-4 h-4 text-stone-700" />
        <h4 className="font-serif text-lg font-bold text-stone-900 tracking-tight">
          Why this verdict?
        </h4>
      </div>

      <p className="text-xs sm:text-sm text-stone-600 mb-6 leading-relaxed">
        Step-by-step audit showing how the cited evidence establishes the <strong className="text-stone-900">{verdict}</strong> determination:
      </p>

      {/* Step by step reasoning list */}
      <div className="space-y-4">
        {reasoning.map((step) => (
          <div key={step.index} className="flex items-start gap-4">
            <span className="w-7 h-7 rounded-md bg-stone-100 border border-stone-200 text-stone-800 font-mono text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
              {step.index}
            </span>
            <div className="flex-1 min-w-0">
              <h5 className="text-sm font-semibold text-stone-900 mb-1">
                {step.title}
              </h5>
              <p className="text-xs sm:text-sm text-stone-600 leading-relaxed">
                {step.description}
              </p>
            </div>
          </div>
        ))}
      </div>

      {/* AI-assisted analysis transparency card */}
      <div className="mt-7 pt-4 border-t border-stone-100 bg-[#faf9f6] -mx-6 -mb-6 p-5 sm:px-6 rounded-b-xl flex items-start gap-3">
        <div className="p-1.5 rounded-md bg-stone-200/80 text-stone-700 shrink-0 mt-0.5">
          <Sparkles className="w-3.5 h-3.5" />
        </div>
        <div className="text-xs leading-relaxed text-stone-700">
          <span className="font-semibold text-stone-900 block mb-0.5">
            AI-assisted analysis & verification
          </span>
          <p>
            This result was generated by AI using the evidence available to the system. Review the cited sources before relying on the result.
          </p>
        </div>
      </div>
    </div>
  );
};
